from setuptools import setup, find_packages

setup(
    name='film69',
    version='0.2.6',
    packages=find_packages(),
    # install_requires=[
    #     'minimalmodbus',
    #     'transformers',
    #     'sentence-transformers',
    #     'llama-index-vector-stores-milvus',
    #     'llama-index',
    #     'llama-index-embeddings-huggingface',
    #     'pymilvus',
    #     'openai',
    #     'accelerate',
    #     'datasets',
    #     'peft',
    #     'bitsandbytes',
    #     'trl<0.9.0',
    #     'unsloth @ git+https://github.com/unslothai/unsloth.git#egg=unsloth',
    #     # Add additional requirements if needed
    # ],
    install_requires=[
    'setuptools',
    'setuptools-scm',
    'packaging',
    'tyro',
    'transformers',
    'datasets',
    'sentencepiece',
    'tqdm',
    'psutil',
    'wheel',
    'numpy',
    'accelerate',
    'trl',
    'peft',
    'protobuf',
    'huggingface-hub',
    'hf-transfer',
    'bitsandbytes',
    'xformers',
    'ninja',
    'minimalmodbus',
    'sentence-transformers',
    'llama-index-vector-stores-milvus',
    'llama-index',
    'llama-index-embeddings-huggingface',
    'pymilvus',
    'openai',
],
    author='Watcharaphon Pamayayang',
    author_email='filmmagic45@gmail.com',
    # description='A brief description of the package',  # Update this with your package's description
    url='https://github.com/watcharaphon6912',  # Update this with your project's URL
)
